services:
  granite-plus-proxy:
    ports:
      - "${GRANITE_PLUS_DIRECT_PORT:-8701}:${GRANITE_PLUS_DIRECT_PORT:-8701}"
  granite-nar:
    ports:
      - "${GRANITE_NAR_DIRECT_PORT:-8702}:${GRANITE_NAR_DIRECT_PORT:-8702}"
  granite-base:
    ports:
      - "${GRANITE_BASE_DIRECT_PORT:-8700}:${GRANITE_BASE_DIRECT_PORT:-8700}"

